apiVersion: v1
kind: Service
metadata:
  name: "service-simple-webapp"
  namespace: "simple-webapp"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "simple-webapp"
